version: 2
jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
      - checkout

      - run:
          name: install dependencies
          command: sudo apt-get install bash curl

      - run:
          name: download Go
          command: wget https://golang.org/dl/go1.20.2.linux-amd64.tar.gz
      
      - run:
          name: install Go
          command: sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.20.2.linux-amd64.tar.gz
      
      - run:
          name: set Go path
          command: echo 'export PATH=$PATH:/usr/local/go/bin' >> $BASH_ENV

      - run: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
     
      - run: |
          node -v

      - run: |
          nvm install v16
          node -v
          nvm alias default v16

      - run: |
          node -v

      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

      - run:
          name: Install dependencies
          command: npm install
          
      - run:
          name: Build UI
          command: npm run client-build

      - run:
          name: Build and publish dockerfiles
          command: sh docker.sh

workflows:
  version: 2
  build-all:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master